/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pendaftaranmahasiswabaru;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.nio.charset.StandardCharsets;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Putra Nurhuda Makatita
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private UserDataModel userModel046 = new UserDataModel();

    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programTitle046 = new javax.swing.JLabel();
        pageTitle046 = new javax.swing.JLabel();
        userNameField046 = new javax.swing.JTextField();
        userNameLabel046 = new javax.swing.JLabel();
        passwordLabel046 = new javax.swing.JLabel();
        submitBtn046 = new javax.swing.JButton();
        passwordField046 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programTitle046.setText("Pendaftaran Mahasiswa Baru");

        pageTitle046.setText("Login");

        userNameLabel046.setText("Username");

        passwordLabel046.setText("Password");

        submitBtn046.setText("Submit");
        submitBtn046.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtn046ActionPerformed(evt);
            }
        });

        passwordField046.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField046ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(117, 117, 117)
                                                        .addComponent(programTitle046,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 161,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(181, 181, 181)
                                                        .addComponent(pageTitle046,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(userNameLabel046,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(passwordLabel046,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(submitBtn046,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(userNameField046,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 161,
                                                                Short.MAX_VALUE)
                                                        .addComponent(passwordField046))))
                                .addContainerGap(122, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(programTitle046)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pageTitle046)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userNameField046, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userNameLabel046))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel046)
                                        .addComponent(passwordField046, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(submitBtn046)
                                .addContainerGap(91, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtn046ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_submitBtn046ActionPerformed

        String username046 = userNameField046.getText();
        String password046 = passwordField046.getText();

        ArrayList<Map<String, String>> userData046 = userModel046.getData();

        for (Map<String, String> user046 : userData046) {
            if (user046.containsKey("username") && user046.containsKey("password")
                    && user046.get("username").equals(username046)
                    && user046.get("password").equals(generateSHA1(password046))) {

                JOptionPane.showMessageDialog(this, "Login Berhasil");
                HomeScreen homeScreen046 = new HomeScreen();
                homeScreen046.jalan();
                this.setVisible(false);
                return;

            }
        }

        JOptionPane.showMessageDialog(this, "Akun tidak ditemukan!");
    }// GEN-LAST:event_submitBtn046ActionPerformed

    private void passwordField046ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordField046ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordField046ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void jalan() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pageTitle046;
    private javax.swing.JPasswordField passwordField046;
    private javax.swing.JLabel passwordLabel046;
    private javax.swing.JLabel programTitle046;
    private javax.swing.JButton submitBtn046;
    private javax.swing.JTextField userNameField046;
    private javax.swing.JLabel userNameLabel046;
    // End of variables declaration//GEN-END:variables

    // logics encryption pakai sha1:
    private static String generateSHA1(String input) {
        try {
            MessageDigest md046 = MessageDigest.getInstance("SHA-1");
            byte[] messageDigest046 = md046.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString046 = new StringBuilder();
            for (byte b046 : messageDigest046) {
                hexString046.append(String.format("%02x", b046));
            }
            return hexString046.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

}
