/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pendaftaranmahasiswabaru;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Putra Nurhuda Makatita
 */
public class MahasiswaForm extends javax.swing.JFrame {

    private HomeScreen parent046;
    private MahasiswaDataModel mahasiswaModel046 = new MahasiswaDataModel();
    private String method046;

    /**
     * Creates new form MahasiswaForm
     */
    public MahasiswaForm(HomeScreen parent) {
        this.parent046 = parent;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionTitle046 = new javax.swing.JLabel();
        nimLabel046 = new javax.swing.JLabel();
        namaLabel046 = new javax.swing.JLabel();
        namaField046 = new javax.swing.JTextField();
        jurusanLabel046 = new javax.swing.JLabel();
        jurusanComboBox046 = new javax.swing.JComboBox<>();
        asalSekolahLabel046 = new javax.swing.JLabel();
        asalSekolahField046 = new javax.swing.JTextField();
        saveBtn046 = new javax.swing.JButton();
        cancelBtn046 = new javax.swing.JButton();
        nimComboBox046 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        actionTitle046.setText("Add Data Mahasiswa");

        nimLabel046.setText("NIM");

        namaLabel046.setText("Nama");

        jurusanLabel046.setText("Jurusan");

        jurusanComboBox046.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        asalSekolahLabel046.setText("Asal Sekolah");

        saveBtn046.setText("Save");
        saveBtn046.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn046ActionPerformed(evt);
            }
        });

        cancelBtn046.setText("Cancel");
        cancelBtn046.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn046ActionPerformed(evt);
            }
        });

        nimComboBox046.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auto generated" }));
        nimComboBox046.setEnabled(false);

        nimComboBox046.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimComboBox046ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveBtn046, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn046, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(asalSekolahLabel046, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(nimLabel046, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jurusanLabel046, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(namaLabel046, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(actionTitle046, javax.swing.GroupLayout.DEFAULT_SIZE, 186,
                                                Short.MAX_VALUE)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(namaField046)
                                                .addComponent(jurusanComboBox046, 0, 186, Short.MAX_VALUE)
                                                .addComponent(asalSekolahField046)
                                                .addComponent(nimComboBox046, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))
                                .addContainerGap(116, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(actionTitle046)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nimLabel046)
                                        .addComponent(nimComboBox046, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namaLabel046)
                                        .addComponent(namaField046, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jurusanLabel046)
                                        .addComponent(jurusanComboBox046, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(asalSekolahLabel046)
                                        .addComponent(asalSekolahField046, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveBtn046)
                                        .addComponent(cancelBtn046))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nimComboBox046ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nimComboBox046ActionPerformed

        if (nimComboBox046.getItemCount() > 0) {
            String nim046 = nimComboBox046.getSelectedItem().toString();

            if (nim046.equals("auto generated")) {
                resetForm();
                return;
            }

            Map<String, String> dataMahasiswa046 = mahasiswaModel046.getDataByNim(nim046);
            namaField046.setText(dataMahasiswa046.get("nama"));
            jurusanComboBox046.setSelectedItem(dataMahasiswa046.get("jurusan"));
            asalSekolahField046.setText(dataMahasiswa046.get("asalSekolah"));
        }
    }// GEN-LAST:event_nimComboBox046ActionPerformed

    private void cancelBtn046ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBtn046ActionPerformed
        this.dispose();
    }// GEN-LAST:event_cancelBtn046ActionPerformed

    private void saveBtn046ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveBtn046ActionPerformed
        if (this.method046.equals("add")) {
            String nama046 = namaField046.getText();
            String jurusan046 = jurusanComboBox046.getSelectedItem().toString();
            String asalSekolah046 = asalSekolahField046.getText();

            if (mahasiswaModel046.saveData(nama046, jurusan046, asalSekolah046)) {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");
                this.parent046.displayList();
                this.dispose();
            }
        } else if (this.method046.equals("update")) {
            String nim046 = nimComboBox046.getSelectedItem().toString();
            String nama046 = namaField046.getText();
            String jurusan046 = jurusanComboBox046.getSelectedItem().toString();
            String asalSekolah046 = asalSekolahField046.getText();

            if (mahasiswaModel046.updateData(nim046, nama046, jurusan046, asalSekolah046)) {
                JOptionPane.showMessageDialog(null, "Data berhasil disunting.");
                this.parent046.displayList();
                this.dispose();
            }
        } else if (this.method046.equals("delete")) {
            String nim046 = nimComboBox046.getSelectedItem().toString();

            if (mahasiswaModel046.deleteData(nim046)) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus.");
                this.parent046.displayList();
                this.dispose();
            }
        }
    }// GEN-LAST:event_saveBtn046ActionPerformed

    public void add() {
        resetForm();
        this.method046 = "add";
        actionTitle046.setText("Add Data Mahasiswa");

        setDropdownJurusan();
        showAllField();

        nimComboBox046.setEnabled(false);
        this.setVisible(true);
    }

    public void update() {
        resetForm();
        this.method046 = "update";
        actionTitle046.setText("Update Data Mahasiswa");

        setDropdownNIM();
        setDropdownJurusan();
        showAllField();

        nimComboBox046.setEnabled(true);
        this.setVisible(true);
    }

    public void delete() {
        resetForm();
        this.method046 = "delete";
        actionTitle046.setText("Delete Data Mahasiswa");

        setDropdownNIM();
        hideAllField();

        nimComboBox046.setEnabled(true);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionTitle046;
    private javax.swing.JTextField asalSekolahField046;
    private javax.swing.JLabel asalSekolahLabel046;
    private javax.swing.JButton cancelBtn046;
    private javax.swing.JComboBox<String> jurusanComboBox046;
    private javax.swing.JLabel jurusanLabel046;
    private javax.swing.JTextField namaField046;
    private javax.swing.JLabel namaLabel046;
    private javax.swing.JComboBox<String> nimComboBox046;
    private javax.swing.JLabel nimLabel046;
    private javax.swing.JButton saveBtn046;
    // End of variables declaration//GEN-END:variables

    // setDropdown jurusan
    private void setDropdownJurusan() {
        jurusanComboBox046.removeAllItems();
        jurusanComboBox046.addItem("Teknik Informatika");
        jurusanComboBox046.addItem("Teknik Industri");
        jurusanComboBox046.addItem("Desain Komunikasi Visual");

    }

    private void setDropdownNIM() {
        nimComboBox046.removeAllItems(); // Reset isi dropdown dulu
        nimComboBox046.addItem("auto generated");
        // ambil data nim mahasiswa:
        ArrayList<Map<String, String>> dataMahasiswa046 = mahasiswaModel046.getData();
        for (Map<String, String> user046 : dataMahasiswa046) {
            nimComboBox046.addItem(user046.get("nim"));
        }
    }

    private void resetForm() {
        nimComboBox046.setSelectedIndex(0);
        namaField046.setText("");
        jurusanComboBox046.setSelectedIndex(0);
        asalSekolahField046.setText("");
    }

    private void hideAllField() {
        namaField046.setEnabled(false);
        nimComboBox046.setEnabled(false);
        jurusanComboBox046.setEnabled(false);
        asalSekolahField046.setEnabled(false);

    }

    private void showAllField() {
        namaField046.setEnabled(true);
        nimComboBox046.setEnabled(true);
        jurusanComboBox046.setEnabled(true);
        asalSekolahField046.setEnabled(true);
    }
}
